# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': '\u041c\u0435\u0441\u0442\u043e',
                'verbose_name_plural': '\u041c\u0435\u0441\u0442\u0430',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': '\u0421\u043f\u043e\u0440\u0442',
                'verbose_name_plural': '\u0421\u043f\u043e\u0440\u0442',
            },
        ),
        migrations.CreateModel(
            name='Tourney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('participants', models.IntegerField(default=10, verbose_name=b'\xd0\xa3\xd1\x87\xd0\xb0\xd1\x81\xd1\x82\xd0\xbd\xd0\xb8\xd0\xba\xd0\xb8')),
                ('date_start', models.DateField(verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbd\xd0\xb0\xd1\x87\xd0\xb0\xd0\xbb\xd0\xb0')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbe\xd0\xba\xd0\xbe\xd0\xbd\xd1\x87\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f')),
                ('date_in', models.DateField(blank=True, null=True, verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xb7\xd0\xb0\xd0\xb5\xd0\xb7\xd0\xb4\xd0\xb0')),
                ('date_out', models.DateField(blank=True, null=True, verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbe\xd1\x82\xd1\x8a\xd0\xb5\xd0\xb7\xd0\xb4\xd0\xb0')),
                ('time_text', models.TextField(blank=True, null=True, verbose_name=b'\xd0\x92\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8f \xd0\xb4\xd0\xbb\xd1\x8f \xd0\xb2\xd1\x81\xd0\xb5\xd1\x85')),
                ('time_vfd', models.TextField(blank=True, null=True, verbose_name=b'\xd0\x92\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8f \xd0\xb4\xd0\xbb\xd1\x8f \xd0\xbc\xd0\xb5\xd0\xb4\xd0\xb8\xd0\xba\xd0\xbe\xd0\xb2')),
                ('dt_start', models.DateTimeField(blank=True, null=True, verbose_name=b'\xd0\x9d\xd0\xb0\xd1\x87\xd0\xb0\xd0\xbb\xd0\xbe \xd1\x81\xd0\xbe\xd1\x80\xd0\xb5\xd0\xb2\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb9')),
                ('dt_opening', models.DateTimeField(blank=True, null=True, verbose_name=b'\xd0\x9e\xd1\x82\xd0\xba\xd1\x80\xd1\x8b\xd1\x82\xd0\xb8\xd0\xb5')),
                ('dt_closing', models.DateTimeField(blank=True, null=True, verbose_name=b'\xd0\x97\xd0\xb0\xd0\xba\xd1\x80\xd1\x8b\xd1\x82\xd0\xb8\xd0\xb5')),
                ('closing_by_end', models.BooleanField(default=False, verbose_name=b'\xd0\x97\xd0\xb0\xd0\xba\xd1\x80\xd1\x8b\xd1\x82\xd0\xb8\xd0\xb5 \xd0\xbf\xd0\xbe \xd0\xbe\xd0\xba\xd0\xbe\xd0\xbd\xd1\x87\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8e')),
                ('judje_sum', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name=b'\xd0\xa1\xd1\x83\xd0\xb4\xd0\xb5\xd0\xb9\xd1\x81\xd0\xba\xd0\xb8\xd0\xb5')),
                ('reward_sum', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb3\xd1\x80\xd0\xb0\xd0\xb4\xd0\xbd\xd0\xb0\xd1\x8f')),
                ('print_sum', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name=b'\xd0\x9f\xd0\xb5\xd1\x87\xd0\xb0\xd1\x82\xd0\xbd\xd0\xb0\xd1\x8f')),
                ('resp_org', models.CharField(default=b'\xd0\x9c\xd0\xb8\xd0\xbd\xd1\x81\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82', max_length=250, verbose_name=b'\xd0\x9e\xd1\x82\xd0\xb2. \xd0\xbe\xd1\x80\xd0\xb3\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb7\xd0\xb0\xd1\x86\xd0\xb8\xd1\x8f')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportapp.Location', verbose_name=b'\xd0\x9c\xd0\xb5\xd1\x81\xd1\x82\xd0\xb0')),
            ],
            options={
                'ordering': ['date_start'],
                'verbose_name': '\u0421\u043e\u0440\u0435\u0432\u043d\u043e\u0432\u0430\u043d\u0438\u0435',
                'verbose_name_plural': '\u0421\u043e\u0440\u0435\u0432\u043d\u043e\u0432\u0430\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name=b'\xd0\xa4\xd0\x98\xd0\x9e')),
                ('position', models.CharField(max_length=100, verbose_name=b'\xd0\x94\xd0\xbe\xd0\xbb\xd0\xb6\xd0\xbd\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c')),
            ],
            options={
                'ordering': ['fio'],
                'verbose_name': '\u0420\u0430\u0431\u043e\u0442\u043d\u0438\u043a',
                'verbose_name_plural': '\u0420\u0430\u0431\u043e\u0442\u043d\u0438\u043a\u0438',
            },
        ),
        migrations.AddField(
            model_name='tourney',
            name='resp_gov',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_gov', to='sportapp.Worker', verbose_name=b'\xd0\x9e\xd1\x82\xd0\xb2. \xd0\xbf\xd1\x80\xd0\xb0\xd0\xb2-\xd0\xb2\xd0\xbe'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='resp_uso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_uso', to='sportapp.Worker', verbose_name=b'\xd0\x9e\xd1\x82\xd0\xb2. \xd0\xa3\xd0\xa1\xd0\x9e'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='resp_zam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_zam', to='sportapp.Worker', verbose_name=b'\xd0\x9e\xd1\x82\xd0\xb2. \xd0\xb7\xd0\xb0\xd0\xbc'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportapp.Sport', verbose_name=b'\xd0\xa1\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82'),
        ),
    ]
