# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourney',
            name='typer',
            field=models.CharField(choices=[(b'1', b'\xd0\x9c\xd0\xb8\xd0\xbd\xd1\x81\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82'), (b'2', b'\xd0\x92\xd1\x8b\xd0\xb5\xd0\xb7\xd0\xb4'), (b'3', b'\xd0\x94\xd1\x80\xd1\x83\xd0\xb3\xd0\xbe\xd0\xb5')], default=1, max_length=25),
        ),
    ]
